# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        image: bitnami/laravel:9
        ports:
            - '8000:8000'
        command:
            - ./run.sh
        environment:
            DB_HOST: mysql
            DB_PORT: 3306
            DB_USERNAME: 'collective'
            DB_DATABASE: 'collective'
            DB_PASSWORD: 'test'
        volumes:
            - '.:/app'
        depends_on:
            - mysql
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'collective'
            MYSQL_USER: 'collective'
            MYSQL_PASSWORD: 'test'
        volumes:
            - 'mysql-data:/var/lib/mysql'
volumes:
    mysql-data:
        driver: local
